// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "NATS Monitoring Project",
            "url": "http://github.com/nats-monitoring"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get JetStream account information",
                "responses": {
                    "200": {
                        "description": "Account information",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get NATS connections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ConnectionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connections/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Terminate a connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/consumers": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "List all consumers across all streams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/consumers/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Get consumer by name across all streams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get dashboard statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.DashboardStatsResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.DashboardStatsResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get system health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics/rates": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get rate metrics",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 60,
                        "description": "Duration in seconds",
                        "name": "duration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rate metrics",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics/system": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get system metrics",
                "responses": {
                    "200": {
                        "description": "System metrics",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/server/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get server information",
                "responses": {
                    "200": {
                        "description": "Server information",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/streams": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "List all streams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nats-monitoring_internal_dto.StreamResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Create a new stream",
                "parameters": [
                    {
                        "description": "Stream creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.CreateStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.StreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Get stream details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.StreamResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Update a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Stream update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.UpdateStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.StreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Delete a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Create a consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consumer creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.CreateConsumerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Get consumer details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Update a consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consumer update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.UpdateConsumerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Delete a consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/ack": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Acknowledge a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Acknowledgment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.AckMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.AckMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/lag-reset": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Reset consumer lag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reset lag options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ResetLagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ResetLagResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/nack": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Negatively acknowledge a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Negative acknowledgment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.NackMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/pause": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Pause a consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/pending": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Get pending messages for a consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Maximum number of messages to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.PendingMessagesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/replay": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Replay messages to consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Replay options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ReplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ReplayResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/resume": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Resume a paused consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/consumers/{consumer}/term": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consumers"
                ],
                "summary": "Terminate a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumer name",
                        "name": "consumer",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Termination request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.AckTermMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/messages/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Publish a message to a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message to publish",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.PublishMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/messages/{sequence}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Delete a message from a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message sequence number",
                        "name": "sequence",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/streams/{name}/purge": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Purge messages from a stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Purge options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.PurgeStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.PurgeStreamResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get subject information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.SubjectsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/nats-monitoring_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "nats-monitoring_internal_dto.AckMessageRequest": {
            "type": "object",
            "required": [
                "sequence"
            ],
            "properties": {
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.AckMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.AckTermMessageRequest": {
            "type": "object",
            "required": [
                "sequence"
            ],
            "properties": {
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ConnectionInfo": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "integer"
                },
                "connected_at": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "last_activity": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "subs_count": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.ConnectionsResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nats-monitoring_internal_dto.ConnectionInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ConsumerConfigResponse": {
            "type": "object",
            "properties": {
                "ack_policy": {
                    "type": "string"
                },
                "deliver_policy": {
                    "type": "string"
                },
                "durable": {
                    "type": "string"
                },
                "max_deliver": {
                    "type": "integer"
                },
                "replay_policy": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.ConsumerResponse": {
            "type": "object",
            "properties": {
                "ack_rate": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/nats-monitoring_internal_dto.ConsumerConfigResponse"
                },
                "lag": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "num_pending": {
                    "type": "integer"
                },
                "paused": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "stream": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.CreateConsumerRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "ack_policy": {
                    "type": "string",
                    "enum": [
                        "none",
                        "all",
                        "explicit"
                    ]
                },
                "deliver_policy": {
                    "type": "string",
                    "enum": [
                        "all",
                        "last",
                        "new"
                    ]
                },
                "durable": {
                    "type": "string"
                },
                "filter_subject": {
                    "type": "string"
                },
                "max_deliver": {
                    "type": "integer",
                    "minimum": -1
                },
                "name": {
                    "type": "string"
                },
                "replay_policy": {
                    "type": "string",
                    "enum": [
                        "instant",
                        "original"
                    ]
                }
            }
        },
        "nats-monitoring_internal_dto.CreateStreamRequest": {
            "type": "object",
            "required": [
                "name",
                "storage",
                "subjects"
            ],
            "properties": {
                "max_age": {
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "retention": {
                    "type": "string",
                    "enum": [
                        "limits",
                        "interest",
                        "workqueue"
                    ]
                },
                "storage": {
                    "type": "string",
                    "enum": [
                        "file",
                        "memory"
                    ]
                },
                "subjects": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "nats-monitoring_internal_dto.DashboardStatsResponse": {
            "type": "object",
            "properties": {
                "bytes": {
                    "type": "integer"
                },
                "connections": {
                    "type": "integer"
                },
                "consumers": {
                    "type": "integer"
                },
                "messages": {
                    "type": "integer"
                },
                "server_status": {
                    "type": "string"
                },
                "streams": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.HealthResponse": {
            "type": "object",
            "properties": {
                "nats": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.NackMessageRequest": {
            "type": "object",
            "required": [
                "sequence"
            ],
            "properties": {
                "delay": {
                    "description": "Redelivery delay in seconds",
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.PendingMessage": {
            "type": "object",
            "properties": {
                "consumer": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "num_delivered": {
                    "type": "integer"
                },
                "num_pending": {
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                },
                "stream": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.PendingMessagesResponse": {
            "type": "object",
            "properties": {
                "consumer": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nats-monitoring_internal_dto.PendingMessage"
                    }
                },
                "num_ack_pending": {
                    "type": "integer"
                },
                "num_pending": {
                    "type": "integer"
                },
                "stream": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.PublishMessageRequest": {
            "type": "object",
            "required": [
                "subject"
            ],
            "properties": {
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "payload": {
                    "type": "string"
                },
                "reply_to": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.PurgeStreamRequest": {
            "type": "object",
            "properties": {
                "sequence": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.PurgeStreamResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "remaining": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ReplayRequest": {
            "type": "object",
            "properties": {
                "end_seq": {
                    "type": "integer"
                },
                "filter_subject": {
                    "type": "string"
                },
                "start_seq": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ReplayResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "replay_id": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.ResetLagRequest": {
            "type": "object",
            "properties": {
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.ResetLagResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "new_sequence": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.StreamConfigResponse": {
            "type": "object",
            "properties": {
                "max_age": {
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer"
                },
                "retention": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "nats-monitoring_internal_dto.StreamResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/nats-monitoring_internal_dto.StreamConfigResponse"
                },
                "state": {
                    "$ref": "#/definitions/nats-monitoring_internal_dto.StreamStateResponse"
                }
            }
        },
        "nats-monitoring_internal_dto.StreamStateResponse": {
            "type": "object",
            "properties": {
                "bytes": {
                    "type": "integer"
                },
                "consumers": {
                    "type": "integer"
                },
                "delete_marks": {
                    "type": "integer"
                },
                "first_seq": {
                    "type": "integer"
                },
                "first_ts": {
                    "type": "string"
                },
                "last_seq": {
                    "type": "integer"
                },
                "last_ts": {
                    "type": "string"
                },
                "messages": {
                    "type": "integer"
                },
                "num_pending": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.SubjectInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "last_seen": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.SubjectsResponse": {
            "type": "object",
            "properties": {
                "subjects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nats-monitoring_internal_dto.SubjectInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "nats-monitoring_internal_dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "nats-monitoring_internal_dto.UpdateConsumerRequest": {
            "type": "object",
            "properties": {
                "ack_policy": {
                    "type": "string",
                    "enum": [
                        "none",
                        "all",
                        "explicit"
                    ]
                },
                "deliver_policy": {
                    "type": "string",
                    "enum": [
                        "all",
                        "last",
                        "new"
                    ]
                },
                "max_deliver": {
                    "type": "integer",
                    "minimum": -1
                },
                "replay_policy": {
                    "type": "string",
                    "enum": [
                        "instant",
                        "original"
                    ]
                }
            }
        },
        "nats-monitoring_internal_dto.UpdateStreamRequest": {
            "type": "object",
            "properties": {
                "max_age": {
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "replicas": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "NATS Monitoring API",
	Description:      "Comprehensive API for monitoring and managing NATS JetStream instances.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
