apiVersion: v2
name: nats-monitor
description: A Helm chart for NATS Monitoring - Real-time NATS JetStream monitoring dashboard
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - nats
  - monitoring
  - jetstream
  - observability
home: https://github.com/amir-baghshahy/nats-monitor
sources:
  - https://github.com/amir-baghshahy/nats-monitor
maintainers:
  - name: Amir
    email: amir@example.com
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/amir-baghshahy/nats-monitor
    - name: Docs
      url: https://github.com/amir-baghshahy/nats-monitor/blob/main/README.md
